services:

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: bsluser
      POSTGRES_PASSWORD: bslpassword
      POSTGRES_DB: bsldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bsluser -d bsldb"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: bsl-python-backend
    build: ./backend-python
    working_dir: /app
    command: [ "python", "scripts/seed_db.py" ]
    environment:
      DB_URL: postgresql://bsluser:bslpassword@postgres:5432/bsldb
      PYTHONPATH: /app
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  backend:
    image: bsl-python-backend
    build: ./backend-python
    ports:
      - "3001:3001"
    environment:
      DB_URL: postgresql://bsluser:bslpassword@postgres:5432/bsldb
    depends_on:
      migrate:
        condition: service_completed_successfully

  frontend:
    image: bsl-frontend
    build: ./frontend
    ports:
      - "5173:8080"
    depends_on:
      - backend

  tester:
    image: bsl-tester
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - backend
      - frontend
    network_mode: "host"

volumes:
  postgres_data: