apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # PostgreSQL
  - infra/postgres-pvc.yaml
  - infra/postgres-service.yaml
  - infra/postgres-deployment.yaml

  # Backend
  - backend/manifests/configmap.yaml
  - backend/manifests/secret.yaml
  - backend/manifests/imagestream.yaml
  - backend/manifests/service.yaml
  - backend/manifests/deployment.yaml
  - backend/manifests/route.yaml

  # Frontend
  - frontend/manifests/imagestream.yaml
  - frontend/manifests/service.yaml
  - frontend/manifests/deployment.yaml
  - frontend/manifests/route.yaml