apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsl-postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: bsl-postgres

  template:
    metadata:
      labels:
        app: bsl-postgres

    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: postgres
          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: bsluser

            - name: POSTGRES_PASSWORD
              value: bslpassword

            - name: POSTGRES_DB
              value: bsldb

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          emptyDir: { }