apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: bsl-backend-service-prod
spec:
  tags:
    - name: production
      from:
        kind: DockerImage
        name: bslgame/bsl-backend:staging
      importPolicy:
        scheduled: false
      referencePolicy:
        type: Local
