"""initial schema

Revision ID: b90d3ad578b6
Revises: 
Create Date: 2026-06-26 11:49:52.545780

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b90d3ad578b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bsl_classes',
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('class_number')
    )
    op.create_table('microbes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('bsl_level', sa.Integer(), nullable=True),
    sa.Column('lecture_text', sa.Text(), nullable=False),
    sa.Column('feedback_correct', sa.Text(), nullable=False),
    sa.Column('feedback_incorrect', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bsl_level'], ['bsl_classes.class_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('microbes')
    op.drop_table('bsl_classes')
    # ### end Alembic commands ###
