apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bsl-backend-route
  labels:
    router: external
spec:
  host: bsl-backend-route-bsl-game-ohtu-k2026.ext.okd-cs-test-0.k8s.cs.helsinki.fi
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: backend
  port:
    targetPort: 3001